name: hyp3-opera-rtc
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10
  - pip
  # For running
  - hyp3lib>=3,<4
  - asf_search
  - rasterio
  - dem_stitcher
  # For packaging, and testing
  - setuptools
  - setuptools_scm
  - wheel
  - pytest
  - pytest-console-scripts
  - pytest-cov
