name: hyp3-opera-rtc
channels:
  - conda-forge
  - nodefaults
dependencies:
  # For running
  - python>=3.9,<3.10 # restriction to match the python version of OPERA PGE
  - pip
  - gdal>=3.0
  - shapely
  - hyp3lib
  - boto3
  - jinja2
  - burst2safe
  # For packaging, and testing
  - setuptools
  - setuptools_scm
  - wheel
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - pip:
    - -e .[develop]
