name: hyp3-opera-rtc
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - pip
  # For running
  - gdal
  - numpy
  - shapely
  - boto3
  - earthaccess
  - s1reader
  - requests
  - urllib3
  - lxml
  - jinja2
  # For packaging, and testing
  - setuptools
  - setuptools_scm
  - wheel
  - pytest
  - pytest-console-scripts
  - pytest-cov
