name: hyp3-opera-rtc
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python<3.10
  - pip
  # For running
  - gdal
  - numpy
  - shapely
  - requests
  - urllib3
  - lxml
  - jinja2
  - burst2safe
  - s1reader
  # For packaging, and testing
  - setuptools
  - setuptools_scm
  - wheel
  - pytest
  - pytest-console-scripts
  - pytest-cov
