name: hyp3-opera-rtc
channels:
  - conda-forge
  - nodefaults
dependencies:
  # For running
  - python
  - git
  - pip
  - gdal>=3.0
  - shapely
  - hyp3lib
  - boto3
  - jinja2
  - hyp3lib
  - burst2safe
  # For packaging, and testing
  - setuptools
  - setuptools_scm
  - wheel
  - moto[s3]
  - pytest
  - pytest-console-scripts
  - pytest-cov
